#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# -- Exit on errors.

set -eu


# -- Function to print a horizontal line.

print_line() {
    printf "%-25s %-15s %-15s %-20s %-15s %-15s\n" "-------------------------" "---------------" "---------------" "----------------------" "---------------" "---------------"
}


# -- Print header.

print_line
printf "%-25s %-15s %-15s %-20s %-15s %-15s\n" "Device" "Size" "Used" "Mount Point" "Filesystem" "Label"
print_line


# -- Get df -h information and filter relevant columns.

df_info=$(df -h --output=source,size,used,target --exclude-type=tmpfs,devtmpfs | awk 'NR>1 {print $1, $2, $3, $4}' | sort)


# -- Loop through df_info and get filesystem and label information using blkid command.

while read -r device size used mountpoint; do
    filesystem=$(blkid -o value -s TYPE "$device" 2>/dev/null || echo "N/A")
    label=$(blkid -o value -s LABEL "$device" 2>/dev/null || echo "N/A")
    
    printf "%-25s %-15s %-15s %-20s %-15s %-15s\n" "${device:0:25}" "$size" "$used" "${mountpoint:0:20}" "${filesystem:-N/A}" "${label:-N/A}"
done <<< "$df_info"

print_line
