#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Exit on errors.

set -eu


# -- Function to print a horizontal line.

print_line() {
    printf "%-25s %-15s %-15s %-20s %-15s %-15s\n" "-------------------------" "---------------" "---------------" "----------------------" "---------------" "---------------"
}


# -- Print header.

print_line
printf "%-25s %-15s %-15s %-20s %-15s %-15s\n" "Device" "Size" "Used" "Mount Point" "Filesystem" "Label"
print_line


# -- Get df -h information and filter relevant columns.

df_info=$(df -h --output=source,size,used,target --exclude-type=tmpfs,devtmpfs | awk 'NR>1 {print $1, $2, $3, $4}' | sort)


# -- Loop through df_info and get filesystem and label information using blkid command.

while read -r device size used mountpoint; do
    filesystem=$(blkid -o value -s TYPE "$device" 2>/dev/null || echo "N/A")
    label=$(blkid -o value -s LABEL "$device" 2>/dev/null || echo "N/A")
    
    printf "%-25s %-15s %-15s %-20s %-15s %-15s\n" "${device:0:25}" "$size" "$used" "${mountpoint:0:20}" "${filesystem:-N/A}" "${label:-N/A}"
done <<< "$df_info"

print_line
