#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu


## -- Variables

dist=$(grep -oP 'PRETTY_NAME=\K.*' /etc/os-release | tr -d '"')
dbox_url='https://nxos.org/tutorial/how-to-use-distrobox-in-nitrux/'
notes_url='https://nxos.org/notes/'
bug_repo='https://github.com/Nitrux/nitrux-bug-tracker/issues'
vendor='Nitrux Latinoamericana S.C.'
fecha=$(date +%Y)

## --  Format

BOLD='\e[1m'
ITALIC='\e[3m'
UNDERLINE='\e[4m'
NF='\e[0m'

## -- Colors

# BLUE='\033[0;34m'
WHITE='\033[1;37m'
YELLOW='\033[1;33m'
# RED='\033[0;31m'
NC='\033[0m'

## -- Message

echo ' ';
echo '                          =                  ';
echo '                          =     .            ';
echo '                          =     .:::         ';
echo '::+.      ....:......     =         :::      ';
echo '%+-#=  ..:    :-:    .    =            :::.  ';
echo '--#-=-- --    .:#---.     =            .=#%#=';
echo '- .**=#= :      *    .    =         :+#%%%#=.';
echo '-   -# =#.    --     .    =      :+%%%%*-.   ';
echo '        ..  ..  ....      =   -+%%%%*-       ';
echo '                          =-*%%%%+:          ';
echo '                          +%%#+:             ';
echo ' ';
echo ' ';
echo -e "$dist";
echo ' ';
echo -e "(c) $fecha Some Rights Reserved. Made by $vendor";
echo ' ';
echo ' ';
echo -e "${YELLOW}####################${NC}";
echo -e "${YELLOW}# About Nitrux     #${NC}";
echo -e "${YELLOW}####################${NC}";
echo ' ';
echo -e "Thank you for using $dist. ${ITALIC}Powered by Debian, KDE Plasma and Frameworks, and AppImages${NF}.";
echo ' ';
echo -e "We strongly emphasize using AppImages or Flatpaks to install end-user software in $dist.";
echo ' ';
echo -e "However, if you require to use a package manager create a container using ${BOLD}Distrobox${NF}.";
echo ' ';
echo -e "For help creating a container in Nitrux, visit our blog: ${WHITE}${UNDERLINE}$dbox_url${NC}${NF}";
echo ' ';
echo -e "For more information about $dist, visit our blog: ${WHITE}${UNDERLINE}$notes_url${NC}${NF}";
echo ' ';
echo -e "To report a bug in $dist, create a new issue at our bug repository ${WHITE}${UNDERLINE}$bug_repo${NC}${NF}";
echo ' ';
# echo -e "${YELLOW}##################${NC}";
# echo -e "${YELLOW}# Disclaimer     #${NC}";
# echo -e "${YELLOW}##################${NC}";
# echo ' ';
# echo -e "${BOLD}${ITALIC}$vendor does not develop KDE Plasma, KDE Frameworks, Qt, MESA, or the Liquorix kernel${NF}.";
# echo ' ';
