#!/usr/bin/env bash

set -eu


# -- Install the *LATEST* NVIDIA proprietary driver using the official installer.
# -- Download the driver directly from NVIDIA.

BASE_URL="http://download.nvidia.com/XFree86/Linux-x86_64/"
LATEST_URL="${BASE_URL}latest.txt"
USER_AGENT="BrightSign/8.2.55.5 (XT1144) Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.3 Chrome/69.0.3497.128 Safari/537.36"
DESTINATION="$(mktemp -d)"

axel -a -q -k -U "$USER_AGENT" -n 8 "$LATEST_URL" -o "${DESTINATION}/latest.txt"

LATEST_FILE="$(cat "${DESTINATION}/latest.txt")"
FILE_PATH="$(echo "$LATEST_FILE" | awk '{print $2}')"
FULL_URL="${BASE_URL}${FILE_PATH}"

axel -a -q -k -U "$USER_AGENT" -n 8 "$FULL_URL" -o "${DESTINATION}/$(basename "$FILE_PATH")"

rm -f "${DESTINATION}/latest.txt"


# -- Install the build dependencies.

NVIDIA_DRV_DEPS_PKGS='
	acpid
	build-essential
	dkms
	initramfs-tools
	libglvnd-core-dev
	libglvnd-dev
	pkg-config
'

apt install -y --no-install-recommends $NVIDIA_DRV_DEPS_PKGS


# -- Execute the installer.

chmod +x "$DESTINATION"/*
for NV_DRV_RUN in "$DESTINATION"/*; do
    if [ -x "$NV_DRV_RUN" ]; then
        "$NV_DRV_RUN" --dkms -s
    fi
done


# -- Blacklist the Nouveau driver if not already blacklisted.

if ! grep -q "^blacklist nouveau$" /etc/modprobe.d/blacklist.conf; then
    printf '%s\n' "blacklist nouveau" >> /etc/modprobe.d/blacklist.conf
fi


# -- Remove build dependencies.

NVIDIA_DRV_DEV_PKGS='
	libglvnd-core-dev
	libglvnd-dev
'

apt autoremove -y $NVIDIA_DRV_DEV_PKGS
