#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


set -eu

# -- Functions.

is_broken_link() {
    [[ ! -e "$1" ]]
}

trim_path() {
    local path="$1"
    echo "${path}" | rev | cut -d'/' -f1-3 | rev
}


# -- Prompt user for the directory.

read -rp "Enter the directory path: " dir


# -- Determine the appropriate column widths.

symlink_col_width=70
target_col_width=70
status_col_width=10


# -- Header for the output.

printf "%-${symlink_col_width}s %-${target_col_width}s %-${status_col_width}s\n" "Symlink" "Target" "Status"
printf '%.0s-' {1..150}
printf '\n'

find "$dir" -type l -print0 | while IFS= read -r -d '' file; do
    trimmed_symlink_path=$(trim_path "$file")
    target=$(readlink -f "$file")
    trimmed_target_path=$(trim_path "$target")

    if is_broken_link "$file"; then
        printf "\e[1;31m%-${symlink_col_width}s %-${target_col_width}s %-${status_col_width}s\e[0m\n" "$trimmed_symlink_path" "$trimmed_target_path" "BROKEN"
    else
        printf "\e[1;32m%-${symlink_col_width}s %-${target_col_width}s %-${status_col_width}s\e[0m\n" "$trimmed_symlink_path" "$trimmed_target_path" "OK"
    fi
done
