#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


set -eu

# -- Functions.

is_broken_link() {
    [[ ! -e "$1" ]]
}

trim_path() {
    local path="$1"
    echo "${path}" | rev | cut -d'/' -f1-3 | rev
}


# -- Prompt user for the directory.

read -rp "Enter the directory path: " dir


# -- Determine the appropriate column widths.

symlink_col_width=70
target_col_width=70
status_col_width=10


# -- Header for the output.

printf "%-${symlink_col_width}s %-${target_col_width}s %-${status_col_width}s\n" "Symlink" "Target" "Status"
printf '%.0s-' {1..150}
printf '\n'

find "$dir" -type l -print0 | while IFS= read -r -d '' file; do
    trimmed_symlink_path=$(trim_path "$file")
    target=$(readlink -f "$file")
    trimmed_target_path=$(trim_path "$target")

    if is_broken_link "$file"; then
        printf "\e[1;31m%-${symlink_col_width}s %-${target_col_width}s %-${status_col_width}s\e[0m\n" "$trimmed_symlink_path" "$trimmed_target_path" "BROKEN"
    else
        printf "\e[1;32m%-${symlink_col_width}s %-${target_col_width}s %-${status_col_width}s\e[0m\n" "$trimmed_symlink_path" "$trimmed_target_path" "OK"
    fi
done
