#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Exit on errors.

set -eu


# -- Set program name and version.

TOOL_NAME="OTA Creation Tool"
TOOL_SHRT_NAME="mkota"
TOOL_VERSION="0.0.1_$(date +%Y%m%d)"
VENDOR='Nitrux Latinoamericana S.C.'
FECHA=$(date +%Y)


# -- Print informative messages to stderr.

puts_info() {
	if [ -n "$1" ]; then
		printf "%s: \e[34mInfo:\e[0m %s\n" "$TOOL_NAME" "$*" >&2
	fi
}


# -- Print success messages to stderr.

puts_success() {
	if [ -n "$1" ]; then
		printf "%s: \e[32mSuccess:\e[0m %s\n" "$TOOL_NAME" "$*" >&2
	fi
}


# -- Print error messages to stderr.

puts_error() {
	if [ -n "$1" ]; then
		printf "%s: \e[31mError:\e[0m %b\n" "$TOOL_NAME" "$*" >&2
	fi
}


# -- Print messages or text using multiple lines to stderr.

print_message() {
	if [ -n "$1" ]; then
		printf "%s\n" "$@" >&2
	fi
}


# -- Print warning messages to stderr.

puts_warning() {
    if [ -n "$1" ]; then
        printf "%s: \e[33mWarning:\e[0m %s\n" "$TOOL_NAME" "$*" >&2
    fi
}


# -- Check if any arguments are passed.

if [ $# -eq 0 ]; then
    puts_error "No arguments provided to $TOOL_NAME, quitting."
    exit 1
fi


# -- Check if any arguments are passed

if [ $# -eq 0 ]; then
    puts_error "No arguments provided to $TOOL_NAME, quitting."
    exit 1
fi


# -- Display an error when no flag is used.

error () {
  puts_error "$TOOL_SHRT_NAME: \e[31mError:\e[0m: $*" >&2
  exit 1
}


# -- Ensure dialog is installed.

if ! command -v dialog >/dev/null 2>&1; then
    echo "Error: 'dialog' command not found. Please install dialog and try again."
    exit 1
fi


# -- Functions.

mksqs() {
    local ROOT=("sudo" "mksquashfs" "$@")

    if ! command -v "${ROOT[0]}" >/dev/null 2>&1; then
        puts_error "Error: '${ROOT[0]}' command not found. Please make sure it's installed and try again."
        return 1
    fi

    "${ROOT[@]}"
}

unsqs() {
    local ROOT=("sudo" "unsquashfs" "$@")

    if ! command -v "${ROOT[0]}" >/dev/null 2>&1; then
        puts_error "Error: '${ROOT[0]}' command not found. Please make sure it's installed and try again."
        return 1
    fi

    "${ROOT[@]}"
}

check_etc_paths() {
    for item in "$@"; do
        if [[ $item == /etc* ]]; then
            puts_error "Paths from /etc are not allowed. Exiting."
            exit 1
        fi
    done
}


# -- Use a log file. Check permissions and handle error.

LOG_FILE="/var/log/mkota.log"

if [ -f "$LOG_FILE" ] || touch "$LOG_FILE" 2>/dev/null; then
    if [ -w "$LOG_FILE" ]; then
        puts_info "$TOOL_NAME log file ready for use."
    else
        puts_error "$TOOL_NAME does not have write permissions for $LOG_FILE."
    fi
else
    puts_error "Unable to create or locate $TOOL_NAME log file."
fi


#   ====== START ======

# -- Flag parsing and main operational logic.
(
	while [ $# -gt 0 ]; do
		case "$1" in
				-h | --help )
					print_message "$TOOL_NAME" \
					"" \
					"Description:" \
					"" \
					"    $TOOL_NAME or $TOOL_SHRT_NAME is a utility to create OTA-style files using the SquashFS archiving format for Nitrux OS." \
					"    ⚠️ Important: $TOOL_SHRT_NAME is intended to work exclusively in Nitrux OS, and using this utility in other distributions will break them or not work at all." \
					"" \
					"    Report bugs at: https://github.com/Nitrux/nitrux-bug-tracker/issues." \
					"" \
					"Options:" \
					"    -h or --help                 Show this help." \
					"    -v or --version              Show the version." \
					"    -d or --debug                Enable verbose output." \
					"" \
					"Operations:" \
					"    create            Initializes the process to create an OTA-style SquashFS file." \
					"" \
					"Usage:" \
					"    sudo $TOOL_SHRT_NAME <flag> (operation)" \
					"" \
					"Examples:" \
					"    sudo $TOOL_SHRT_NAME create" \
					"    sudo $TOOL_SHRT_NAME -d create"
					exit
					;;

				-v | --version )
					print_message "$TOOL_NAME" \
					"" \
					"Version: $TOOL_VERSION." \
					"" \
					"The license used for this program is: BSD-3-Clause." \
					"" \
					"Authors:" \
					"" \
					"    Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>" \
					"" \
					"(c) $FECHA Some Rights Reserved. Made by $VENDOR"
					exit
					;;

				-d | --debug )
					set -x
					shift
					;;

				create )

					if [ "$(id -u)" -ne 0 ]; then
						puts_error "$TOOL_NAME is not running as root, quitting."
						exit 1
					fi

					shift

					ITEMS=("$@")

					if [[ ${#ITEMS[@]} -eq 0 ]]; then
						puts_error "No directories or files specified. Exiting."
						exit 1
					fi

					check_etc_paths "${ITEMS[@]}"

					DEST_FILE="ota-$(date +%Y.%m.%d-%H.%M)-amd64.squashfs"

					if mksqs "${ITEMS[@]}" "$DEST_FILE" -comp zstd -Xcompression-level 22 -b 1048576 -quiet -not-reproducible -no-strip -keep-as-directory; then
						puts_success "SquashFS file created successfully."
					else
						puts_error "Failed to create SquashFS file."
						exit 1
					fi
					
					puts_info "Contents of the SquashFS file:"
					unsqs -l "$DEST_FILE" | tee "$DEST_FILE.contents"

					puts_info "MD5 sum of the SquashFS file:"
					md5sum "$DEST_FILE" | tee "$DEST_FILE.md5sum"

					puts_info "Size of the SquashFS file:"
					du -sh "$DEST_FILE"

					break
					;;

				*)
					puts_error "Unknown option: $1"
					exit 1
					;;
			esac
		shift
	done

) 2>&1 | if [ -w "$LOG_FILE" ]; then tee -a "$LOG_FILE"; else cat; fi


#   ====== END ======
