#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

# -- Exit on errors.

set -eu


# -- Workaround for some laptops with NVIDIA GPUs that use PRIME; this will output the image to external ports.

test -f /usr/share/X11/xorg.conf.d/10-nvidia.conf && {
    echo 'NVIDIA Proprietary Driver installed!, adding X11 configuration.'
        > /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf printf "%s\n" \
            'Section "OutputClass"' \
            '    Identifier "nvidia"' \
            '    MatchDriver "nvidia-drm"' \
            '    Driver "nvidia"' \
            '    Option "PrimaryGPU" "Yes"' \
            '    Option "AllowEmptyInitialConfiguration" "true"' \
            '    Option "AllowExternalGpus" "true"' \
            'EndSection'
        > /usr/share/X11/xorg.conf.d/10-amdgpu.conf printf "%s\n" \
            'Section "OutputClass"' \
            '    Identifier "AMDgpu"' \
            '    MatchDriver "amdgpu"' \
            '    Driver "modsetting"' \
            'EndSection'
        > /usr/share/X11/xorg.conf.d/10-intel.conf printf "%s\n" \
            'Section "OutputClass"' \
            '    Identifier "Intel"' \
            '    MatchDriver "i915"' \
            '    Driver "modsetting"' \
            'EndSection'
        > /etc/modprobe.d/blacklist-nouveau.conf printf "%s\n" \
            'blacklist nouveau'
} || {
    echo 'NVIDIA Proprietary Driver not installed!, skipping X11 configuration.'
}
