#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Exit on errors.

set -eu


# -- Workaround for some laptops with NVIDIA GPUs that use PRIME; this will output the image to external ports.

test -f /usr/share/X11/xorg.conf.d/10-nvidia.conf && {
    echo 'NVIDIA Proprietary Driver installed!, adding X11 configuration.'
        > /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf printf "%s\n" \
            'Section "OutputClass"' \
            '    Identifier "nvidia"' \
            '    MatchDriver "nvidia-drm"' \
            '    Driver "nvidia"' \
            '    Option "PrimaryGPU" "Yes"' \
            '    Option "AllowEmptyInitialConfiguration" "true"' \
            '    Option "AllowExternalGpus" "true"' \
            'EndSection'
        > /usr/share/X11/xorg.conf.d/10-amdgpu.conf printf "%s\n" \
            'Section "OutputClass"' \
            '    Identifier "AMDgpu"' \
            '    MatchDriver "amdgpu"' \
            '    Driver "modsetting"' \
            'EndSection'
        > /usr/share/X11/xorg.conf.d/10-intel.conf printf "%s\n" \
            'Section "OutputClass"' \
            '    Identifier "Intel"' \
            '    MatchDriver "i915"' \
            '    Driver "modsetting"' \
            'EndSection'
        > /etc/modprobe.d/blacklist-nouveau.conf printf "%s\n" \
            'blacklist nouveau'
} || {
    echo 'NVIDIA Proprietary Driver not installed!, skipping X11 configuration.'
}
