#!/usr/bin/env python3

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

import subprocess
import os
import sys
from tqdm import tqdm
import shutil

def download_packages(package_list_file, download_dir):
    if not os.path.exists(package_list_file):
        print(f"Error: Package list file '{package_list_file}' not found.")
        sys.exit(1)

    if not os.path.exists(download_dir):
        print(f"Error: Download directory '{download_dir}' not found.")
        sys.exit(1)

    subprocess.run(['sudo', 'apt', 'update'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    with open(package_list_file, 'r') as f:
        packages = [line.strip() for line in f.readlines()]

    num_packages = len(packages)
    terminal_width = shutil.get_terminal_size().columns
    with tqdm(total=num_packages, desc='Downloading packages', unit='pkg', ncols=terminal_width, bar_format='{desc}: {percentage:3.0f}%|{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}]') as pbar:
        for package in packages:
            os.chdir(download_dir)
            result = subprocess.run(['sudo', 'apt', 'download', package], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            if result.returncode != 0:
                print(f"Package '{package}' not found. Exiting.")
                sys.exit(1)
            pbar.update(1)

    print("\nPackages downloaded successfully.")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Download packages from a list using 'apt download'.")
    parser.add_argument('-f', '--file', required=True, help="Path to the package list file.")
    parser.add_argument('-d', '--directory', required=True, help="Directory to download packages to.")
    args = parser.parse_args()

    download_packages(args.file, args.directory)
