#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# -- Exit on errors.

set -eu


# -- Check if the script is run as root.

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi


# -- Check if at least one username is provided as an argument.

if [ $# -eq 0 ]; then
    echo "Usage: $0 <username1> [<username2> ...]"
    exit 1
fi

output_file="user_info_output.txt"


# -- Iterate through the provided usernames.

for username in "$@"; do
    echo "User: $username" | tee -a "$output_file"

    real_name=$(grep "^$username:" /etc/passwd | cut -d ':' -f 5)
    echo "Real Name: $real_name" | tee -a "$output_file"

    who_info=$(who | awk -v user="$username" '$1 == user { print $2 }')
    terminal=$(echo "$who_info" | awk 'NR==1 {print $1}')
    tty=$(echo "$who_info" | awk 'NR==2 {print $1}')
    echo "TTY: $terminal" | tee -a "$output_file"
    echo "PTY: $tty" | tee -a "$output_file"

    user_shell=$(grep "^$username:" /etc/passwd | cut -d ':' -f 7)
    echo "Shell: $user_shell" | tee -a "$output_file"

    login_time=$(last -w -n 1 "$username" | awk 'NR==1 {print $4, $5, $6, $7, $8}')
    echo "Login Time: $login_time" | tee -a "$output_file"
    echo "--------------------------" | tee -a "$output_file"
done

echo "User information has been written to $output_file."
