#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Exit on errors.

set -eu


# -- Check if the script is run as root.

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi


# -- Check if at least one username is provided as an argument.

if [ $# -eq 0 ]; then
    echo "Usage: $0 <username1> [<username2> ...]"
    exit 1
fi

output_file="user_info_output.txt"


# -- Iterate through the provided usernames.

for username in "$@"; do
    echo "User: $username" | tee -a "$output_file"

    real_name=$(grep "^$username:" /etc/passwd | cut -d ':' -f 5)
    echo "Real Name: $real_name" | tee -a "$output_file"

    who_info=$(who | awk -v user="$username" '$1 == user { print $2 }')
    terminal=$(echo "$who_info" | awk 'NR==1 {print $1}')
    tty=$(echo "$who_info" | awk 'NR==2 {print $1}')
    echo "TTY: $terminal" | tee -a "$output_file"
    echo "PTY: $tty" | tee -a "$output_file"

    user_shell=$(grep "^$username:" /etc/passwd | cut -d ':' -f 7)
    echo "Shell: $user_shell" | tee -a "$output_file"

    login_time=$(last -w -n 1 "$username" | awk 'NR==1 {print $4, $5, $6, $7, $8}')
    echo "Login Time: $login_time" | tee -a "$output_file"
    echo "--------------------------" | tee -a "$output_file"
done

echo "User information has been written to $output_file."
