#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 <Uri Herrera <uri_herrera@nxos.org>>

set -eu


# -- Check if APT exists.

if ! command -v apt >/dev/null 2>&1; then
    echo "Error: 'apt' command not found. Please make sure it's available and try again, quitting."
    exit 1
fi


# -- Add APT configuration.

cp -r "$PWD"/container-setup/configs/files/apt_preferences/* /etc/apt/preferences.d/
cp -r "$PWD"/container-setup/configs/files/apt_conf/* /etc/apt/apt.conf.d/


# -- Source APT commands as functions.
# shellcheck source=/dev/null

source "$PWD"/container-setup/configs/scripts/others/apt-funcs


# -- Add Nitrux repository keys.

add_nitrux_key mauikit


# -- Add build sources.

cp "$PWD"/container-setup/configs/files/sources/* /etc/apt/sources.list.d/


# -- Updated package index.

[ -f /etc/apt/sources.list ] && rm -f /etc/apt/sources.list

update


# -- Upgrade rootfs packages.

upgrade


# -- Install packages to build MauiKit.

INSTALL_BUILD_MAUIKIT_PKGS=(
    appstream
    apt-file
    automake
    autotools-dev
    build-essential
    checkinstall
    cmake
    curl
    devscripts
    equivs
    extra-cmake-modules
    gettext
    git
    gnupg2
    kquickimageeditor-dev
    libexiv2-dev
    libkexiv2qt6-dev
    libkf6archive-dev
    libkf6calendarcore-dev
    libkf6config-dev
    libkf6coreaddons-dev
    libkf6filemetadata-dev
    libkf6i18n-dev
    libkf6iconthemes-dev
    libkf6kio-dev
    libkf6notifications-dev
    libkf6pty-dev
    libkf6sonnet-dev
    libkf6syntaxhighlighting-dev
    libkf6windowsystem-dev
    libleptonica-dev
    libopencv-dev
    libpoppler-private-dev
    libpoppler-qt6-dev
    libtesseract-dev
    libxcb-icccm4-dev
    libxcb-shape0-dev
    lintian
    micro
    nlohmann-json3-dev
    qml6-module-qt5compat-graphicaleffects
    qml6-module-qtquick-controls
    qml6-module-qtquick-shapes
    qt6-5compat-dev
    qt6-base-dev
    qt6-base-private-dev
    qt6-declarative-dev
    qt6-declarative-private-dev
    qt6-multimedia-dev
    qt6-positioning-dev
    qt6-svg-dev
)

install "${INSTALL_BUILD_MAUIKIT_PKGS[@]}"


# -- Install packages for desktop integration.

INSTALL_DESKTOP_INTEGRATION_PKGS=(
    plasma-workspace
)

install "${INSTALL_DESKTOP_INTEGRATION_PKGS[@]}"


# -- Update apt-file index.

db_file_update
