#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 <Uri Herrera <uri_herrera@nxos.org>>

set -eu


# -- Check if APT exists.

if ! command -v apt >/dev/null 2>&1; then
    echo "Error: 'apt' command not found. Please make sure it's available and try again, quitting."
    exit 1
fi


# -- Add APT configuration.

cp -r "$PWD"/container-setup/configs/files/apt_preferences/* /etc/apt/preferences.d/
cp -r "$PWD"/container-setup/configs/files/apt_conf/* /etc/apt/apt.conf.d/


# -- Source APT commands as functions.
# shellcheck source=/dev/null

source "$PWD"/container-setup/configs/scripts/others/apt-funcs


# -- Add Nitrux repository keys.

add_nitrux_key skidrow
add_nitrux_key testing
add_nitrux_key area51
add_nitrux_key mauikit
add_nitrux_key nvidia
add_nitrux_key hyprland


# -- Add build sources.

cp "$PWD"/container-setup/configs/files/sources/{debian,nitrux-ota}.sources /etc/apt/sources.list.d/


# -- Updated package index.

[ -f /etc/apt/sources.list ] && rm -f /etc/apt/sources.list

update


# -- Upgrade rootfs packages.

upgrade


# -- Install packages.

INSTALL_OTA_ENV_PKGS=(
    apt-file
    python3-tqdm
    squashfs-tools
)

install "${INSTALL_OTA_ENV_PKGS[@]}"


# -- Update apt-file index.

db_file_update


# -- Cleanup packages.

autoremove
