######################################
#  Bypass repository metadata checks #
######################################

Acquire::Check-Valid-Until "false";
Acquire::Check-Date "false";

# Install updated package maintainer configuration files without prompting.
Dpkg::Options { "--force-confnew"; };
