#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 <Uri Herrera <uri_herrera@nxos.org>>

set -eu


# -- Environment variables.

export DEBIAN_FRONTEND=noninteractive


# -- Check if APT exists.

if ! command -v apt >/dev/null 2>&1; then
    echo "Error: 'apt' command not found. Please make sure it's available and try again, quitting."
    exit 1
fi


# -- Add APT configuration.

cp -r "$PWD"/container-setup/configs/files/apt_preferences/* /etc/apt/preferences.d/
cp -r "$PWD"/container-setup/configs/files/apt_conf/* /etc/apt/apt.conf.d/


# -- Source APT commands as functions.
# shellcheck source=/dev/null

source "$PWD"/container-setup/configs/scripts/others/apt-funcs


# -- Add Nitrux repository keys.

add_nitrux_key mauikit
add_nitrux_key testing


# -- Add build sources.

cp "$PWD"/container-setup/configs/files/sources/{debian,nitrux-mauikit}.sources /etc/apt/sources.list.d/


# -- Updated package index.

[ -f /etc/apt/sources.list ] && rm -f /etc/apt/sources.list

update


# -- Neutralize systemd-tmpfiles completely.
#   -- When apt installs or upgrades systemd, dpkg executes the package maintainer script (postinst). 
#   -- This script runs systemd-tmpfiles --create to set strict ownership and permissions on system directories.
#   -- The configuration file /usr/lib/tmpfiles.d/tmp.conf instructs systemd-tmpfiles to manage /tmp. 
#   -- Because Distrobox bind-mounts the host /tmp directory into the container, the kernel blocks an unprivileged user namespace from altering host mount permissions.
#   -- Systemd treats this failure as fatal, causing dpkg to exit with an error.

dpkg_divert /usr/bin/systemd-tmpfiles
ln -sf /bin/true /usr/bin/systemd-tmpfiles


# -- Upgrade rootfs packages.

upgrade


# -- Install packages to build MauiKit.

INSTALL_BUILD_MAUIKIT_PKGS=(
    appstream
    apt-file
    automake
    autotools-dev
    build-essential
    checkinstall
    cmake
    curl
    devscripts
    equivs
    extra-cmake-modules
    ffmpeg
    ffmpegthumbs
    gettext
    git
    gnupg2
    kdegraphics-thumbnailers
    kio-extras
    kquickimageeditor-dev
    libarchive-dev
    libavcodec-dev
    libavformat-dev
    libavutil-dev
    libcddb2-dev
    libcdio-cdda-dev
    libcdio-dev
    libcdio-paranoia-dev
    libexiv2-dev
    libgme-dev
    libgtk-3-dev
    libgtk-4-dev
    libjack-jackd2-dev
    libkexiv2qt6-dev
    libkf6archive-dev
    libkf6auth-dev
    libkf6bluezqt-dev
    libkf6calendarcore-dev
    libkf6colorscheme-dev
    libkf6config-dev
    libkf6coreaddons-dev
    libkf6filemetadata-dev
    libkf6i18n-dev
    libkf6iconthemes-dev
    libkf6idletime-dev
    libkf6kio-dev
    libkf6modemmanagerqt-dev
    libkf6networkmanagerqt-dev
    libkf6notifications-dev
    libkf6pty-dev
    libkf6sonnet-dev
    libkf6syntaxhighlighting-dev
    libkf6windowsystem-dev
    liblayershellqtinterface-dev
    libleptonica-dev
    libmp3lame-dev
    libmpcdec-dev
    libmpv-dev
    libogg-dev
    libopencv-dev
    libopus-dev
    libopusfile-dev
    libpam0g-dev
    libpipewire-0.3-dev
    libpoppler-private-dev
    libpoppler-qt6-dev
    libpulse-dev
    libpwquality-dev
    libsecret-1-dev
    libshout-dev
    libsoxr-dev
    libspa-0.2-dev
    libtag1-dev
    libtesseract-dev
    libvorbis-dev
    libwildmidi-dev
    libxcb-icccm4-dev
    libxcb-shape0-dev
    libxcursor-dev
    lintian
    micro
    nlohmann-json3-dev
    qcoro-qt6-dev
    qml6-module-qt5compat-graphicaleffects
    qml6-module-qtquick-controls
    qml6-module-qtquick-shapes
    qt6-5compat-dev
    qt6-base-dev
    qt6-base-private-dev
    qt6-declarative-dev
    qt6-declarative-private-dev
    qt6-multimedia-dev
    qt6-positioning-dev
    qt6-svg-dev
    qt6-webengine-dev
    ripgrep
    tesseract-ocr-all
    wireplumber
)

install "${INSTALL_BUILD_MAUIKIT_PKGS[@]}"


# -- Install packages for desktop integration.

INSTALL_DESKTOP_INTEGRATION_PKGS=(
    luv-icon-theme
    plasma-workspace
)

install "${INSTALL_DESKTOP_INTEGRATION_PKGS[@]}"


# -- Update apt-file index.

db_file_update


# -- Cleanup packages.

autoremove


# -- Create the generic XDG menu file name, so KApplicationTrader::queryByMimeType(...) finds it.

XDG_MENU_SRC="/etc/xdg/menus/plasma-applications.menu"
XDG_MENU_DEST="/etc/xdg/menus/applications.menu"

if [ ! -f "$XDG_MENU_SRC" ]; then
    echo "Warning: Source file '$XDG_MENU_SRC' does not exist."
elif [ ! -e "$XDG_MENU_DEST" ] && [ ! -L "$XDG_MENU_DEST" ]; then
    ln -sv "$XDG_MENU_SRC" "$XDG_MENU_DEST"
fi
